language: node_js
node_js: '0.10'
before_install:
- npm install -g bower
before_script:
- bower install
cache:
  directories:
  - node_modules
before_deploy: sh ./scripts/ci-build.sh
deploy:
- provider: divshot
  environment: development
  api_key:
    secure: avqngaVhM1dtI/PrhoTHkIlTzl5D0iK87x9ksC1p9j0CcZiiLGHAXH38FdRtbKlMXc4eKK8t6ON5KbIU7N4/OZWq8rJ5ZxkU7kc8gKIXDSaqOAtf1SYcMpt7o+A1iFVDhzTA13SEz7uHeTlpkwxOyVatPc/9dE6+MUgUdBV1I3A=
  skip_cleanup: true
  on:
    repo: valet-io/projector-app
    branch: development
- provider: divshot
  environment: staging
  api_key:
    secure: avqngaVhM1dtI/PrhoTHkIlTzl5D0iK87x9ksC1p9j0CcZiiLGHAXH38FdRtbKlMXc4eKK8t6ON5KbIU7N4/OZWq8rJ5ZxkU7kc8gKIXDSaqOAtf1SYcMpt7o+A1iFVDhzTA13SEz7uHeTlpkwxOyVatPc/9dE6+MUgUdBV1I3A=
  skip_cleanup: true
  on:
    repo: valet-io/projector-app
    branch: master
notifications:
  slack:
    secure: T1/4MdXdzio7tOqsGaQVGpJ5fVHcx/Y9BzotsnwpFwbIfpkNZMsu1nGlwU6QC7Of5y/BONeJRvbLrGCyAoknwvKTAVfZlsYta1FbYqfBm9naZ0GmyDCt9riftJK58NrkJI49wYsmBueFo28WJFOXnuWDKIcEoOY7COqKuuL/S2c=
